version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run: mvn install
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - run: mvn test
      
workflows:
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build
