version: 2.1
executors:
  exec:
    docker:
      - image: circleci/openjdk:8-jdk
jobs:
  build_test:
    executor: exec
    steps:
      - checkout
      - run: mvn install -DskipTests
      - run: mvn test
workflows:
  build_test:
    jobs:
      - build_test
