version: 2.1

orbs:
  maven: circleci/maven@0.0.12

jobs:
  build:
    executor: default
    steps:
      - checkout
      - run: mvn install 
  test:
    executor: default
    steps:
      - run: mvn test
      
workflows:
  build_test:
    jobs:
      - build
      - test
