version: 2.1

jobs:
  build:
    docker: 
      - image: ubuntu:14.04
    steps:
      - checkout
      - run: mvn install 
  test:
    docker: 
      - image: ubuntu:14.04
    steps:
      - run: mvn test
      
workflows:
  build_test:
    jobs:
      - build
      - test:
        requires:
          - build
