version: 2.1
executors:
  exec:
    docker:
      - image: circleci/openjdk:8-jdk
commands:
  testcommand:
    description: "Some description"
    parameters:
      some-value:
          type: string
          default: mika
    steps:
      - checkout
      - run: mvn install -DskipTests
      - run: mvn test
      - run: echo Hello << parameters.some-value >>
jobs:
  build_test1:
    executor: exec
    steps:
      - testcommand
  build_test2:
    executor: exec
    steps:
      - testcommand
workflows:
  build_test:
    jobs:
      - build_test1
      - build_test2:
         some-value: zika
