version: 2.1
executors:
  exec:
    docker:
      - image: circleci/openjdk:8-jdk
jobs:
  build:
    executor: exec
    steps:
      - checkout
      - persist_to_workspace:
            root: .
            paths:
                - .
      - run: mvn install -DskipTests
  test:
    executor: exec
    steps:
      - run: mvn test
      
workflows:
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build
