version: 2.1

jobs:
  build:
    steps:
      -checkout
      -mvn install 
  test:
    steps:
      -mvn test
      
workflows:
  build_test:
    jobs:
      - build
      - test
        requires:
          - build
